server {
    listen 80;
    server_name site.local;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name site.local;

    ssl_certificate /etc/nginx/certs/site.local.crt;
    ssl_certificate_key /etc/nginx/certs/site.local.key;

    location / {
        proxy_pass http://wordpress:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location = /wp-login.php {
        # allow 127.0.0.1;
        allow 194.87.200.163;
        # allow 10.0.2.2; #vbox
        deny all;

        proxy_pass http://wordpress:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /wp-admin/ {
        # allow 127.0.0.1;
        allow 194.87.200.163;
        # allow 10.0.2.2; #vbox
        deny all;

        proxy_pass http://wordpress:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80;
    server_name metrics.local;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name metrics.local;

    ssl_certificate /etc/nginx/certs/metrics.local.crt;
    ssl_certificate_key /etc/nginx/certs/metrics.local.key;

    location / {
        proxy_pass http://grafana:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}