name: CI

on:
  push:
    branches: [ main, master, dev-ci-cd ]
  pull_requests:

jobs:
  compose-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      uses: actions/checkout@v4

      - name: validate docker-compose
      run: docker compose config

      - name: start stack
      run: docker compose up -d

      - name: wait for containers
      run: sleep 100

      - name: check if containers running
      run: docker compose ps | grep -q -E "wordpress|nginx|prometheus|grafana|mysql|node"

      - name: show failure logs
      if: failure()
      run: docker compose logs

      - name: stop stack
      if: always()
      run: docker compose down -v

